name: Tiny Computer Hacks
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60757
title: Tiny computers put to use in RL
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c6c7cb'
    - '#171516'
    - '#535564'
    - '#fae100'
  brandStrength: 0.6875
  lightness: 0.7641539201140404
  saturation: 0.7040023882873356
  rhythmicContrast: 0.23558064317330718
purpose: []
