name: Tiny Computer Hacks
favicon: null
layout_spectrum: 0.43193
typography_spectrum: 0.60757
title: Tiny computers put to use in RL
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a5eb2'
    - '#00030c'
    - '#4f92e1'
    - '#162232'
    - '#fefcff'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.7040023882873356
  rhythmicContrast: 0.23558064317330718
purpose: []
